export enum NotificationType {
  NEW_ERRAND_AVAILABLE = 'NEW_ERRAND_AVAILABLE',
  ERRAND_ASSIGNED = 'ERRAND_ASSIGNED',
  ERRAND_UPDATED = 'ERRAND_UPDATED',
  ERRAND_CANCELED = 'ERRAND_CANCELED',
  START_REMINDER = 'START_REMINDER',
  ERRAND_COMPLETED_CONFIRMATION = 'ERRAND_COMPLETED_CONFIRMATION',
  RUNNER_ACCEPTED = 'RUNNER_ACCEPTED',
  RUNNER_ON_THE_WAY = 'RUNNER_ON_THE_WAY',
  RUNNER_ARRIVED = 'RUNNER_ARRIVED',
  ERRAND_COMPLETED = 'ERRAND_COMPLETED',
  ERRAND_UNASSIGNED = 'ERRAND_UNASSIGNED',
}
